### ISSUE TITLE
Memory research pattern cannot find FoV in COD:Ghosts SP

### ISSUE THREAD

**Issue by JornC** [AgentRev/CoD-FoV-Changers#1]
![image](https://user-images.githubusercontent.com/1552366/60401398-1eb86c00-9b81-11e9-8fb5-d9c1d9469422.png)

**Comment by AgentRev** [comment]
https://github.com/AgentRev/CoD-FoV-Changers/commit/b8aaaca66976f9954e5cd2efd1d51e3c772f4572
