### ISSUE TITLE
[CoD: Ghosts SP] Memory research pattern can't find FoV offset

### ISSUE THREAD

**Issue by WANGJIEKE** [AgentRev/CoD-FoV-Changers#2]
![Snipaste_2019-10-04_18-23-23](https://user-images.githubusercontent.com/21030118/66247671-70b6e380-e6d4-11e9-8b4a-f897daf97e67.png)

**Comment by AgentRev** [comment]
Try waiting until the map is loaded before starting the Changer

**Comment by WANGJIEKE** [comment]
Solved. Thanks.
